site_name: pykit-tools
repo_url: https://github.com/SkylerHu/pykit-tools
docs_dir: .

theme:
  name: readthedocs
#  name: material
  language: zh

nav:
  - 首页: README.md
  - 文档: docs/Reference.md
  - Release Notes: docs/CHANGELOG-1.x.md
  - 贡献者指南: docs/CONTRIBUTING.md

plugins:
  - same-dir
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [pykit_tools]
          options:
            heading_level: 3
            show_root_heading: true
            show_symbol_type_heading: true
#            show_symbol_type_toc: true
            show_source: false
          selection:
            docstring_style: google
